- package-lock.json
- package.json
- src/pages/RankingPage.jsx
- src/styles/rankingPage/RankingPage.module.css
- Closes #10
어떤 변경 사항이 있나요?
1. ## 작업 내용
1위영역 -> 2위영역 -> 3위영역 순으로 랭킹이 표시됩니다.
-
> 🎨 [Design/#10]: 1등급 경쟁 페이지 애니메이션 추가

- src/components/afterShootingPage/QuestionSection.jsx
- src/pages/AfterShootingPage.jsx
- src/pages/ExplanationPage.jsx
- src/pages/SimilarQuestionPage.jsx
- src/styles/global/Header.module.css
- src/styles/similarQuestionPage/explanationCard.module.css
x
어떤 변경 사항이 있나요?
1. 헤더 z-index 수정 -> 모달 오버레이가 헤더보다 위에 있도록 수정
2. 헤더 추가
> 🎨 Design: 헤더 추가

- src/apis/axios.js
- src/components/NickNamePage/NextButton/NextButton.jsx
> ✨  닉네임 중복 확인2

- src/components/CharacterSelectPage/CharacterButton/CharacterButton.jsx
- src/components/NickNamePage/NicknameInput/NicknameInput.jsx
- src/pages/NickNamePage.jsx
닉네임과 캐릭터 정보를 patch하는 과정에서 생긴 오류를 해결했습니다
> 🐛 온보딩 patch 오류 설정

- src/components/CharacterSelectPage/CharacterButton/CharacterButton.jsx
닉네임 캐릭터 api 전송 과정에서 생기는 500오류 해결 진행중입니다.
> 🐛 온보딩 patch 오류 설정 3

- src/components/CharacterSelectPage/CharacterButton/CharacterButton.jsx
🐛 온보딩 patch 오류 설정 5
url 설정 및 오류 처리를 위해서 배포 사이트에서만 온보딩 작업이 가능합니다. 
다수의 머지 양해 부탁드립니다.
> 🐛 온보딩 patch 오류 설정 5

- src/pages/CharacterSelectPage.jsx
> 🐛 온보딩 캐릭터 이미지 get 오류

- src/apis/questionApi.js
- src/components/HomePage/ImageSlider/ImageSlider.jsx
- src/pages/HomePage.jsx
- Closes #38 
- Closes #39 
- Closes #40 
어떤 변경 사항이 있나요?
1. ## 온보딩 API 연결
-> 토큰 정보가 공개되면 안되므로, 배포 페이지에서 실제 체험해주세요
- 회원가입이 된 사람도 다시 온보딩 되는 상태입니다. 해당 부분 수정하겠습니다. 
1, 오류 생기면 수정 예정
2. 메인 화면 닉네임 및 크레딧 api연결 ( 백엔드 구현 완료 되면)
3. 슬라이드 이미지 api 연결
4. 작은 팝업 api 연결
5. 큰 팝업 api 연결
> [Feat] 최근 5문제 api 연결 진행 중

- package-lock.json
- package.json
- src/components/afterShootingPage/ButtonSection.jsx
- src/components/afterShootingPage/NoteCard.jsx
- src/components/afterShootingPage/NoteSection.jsx
- src/styles/afterShootingPage/noteCard.module.css
- Closes #86 
- Closes #87 
어떤 변경 사항이 있나요?
1. ## 문제 저장 후 저장하기 버튼 ui변경
2. ## 공학용 계산기 컴포넌트 연결
> [Feat/#86#87] 저장하기 버튼 변경 및 공학용 계산기 추가

- src/pages/GoogleCallbackPage.jsx
- Closes #
어떤 변경 사항이 있나요?
1. ## 작업 내용
- 루트 설정
- 토큰 재발급 설정
- 백엔드 리다이랙트를 로컬로 설정할 경우 백엔드의 여러 설정도 같이 수정해야 되는 거 같습니다. 따라서 불가피하게 배포 후 결과를 확인하는 지금처럼 진행해야 될거 같습니다.
> ✨ Feat: 재로그인 시 메인으로 연결

- src/pages/GoogleCallbackPage.jsx
재로그인 시 메인 화면으로 연결
어떤 변경 사항이 있나요?
1. ## 오류 유형 확인
가능한 문제 중에 어떤 오류인지 확인하기
1. tokenResponse.data.result가 실제 토큰이 아닐 수 있음
2. JWT 디코딩 과정에서 에러가 발생하면 catch 블록으로 이동
3. catch 블록에서 에러를 던지면 최상위 catch 블록에서 이를 잡아 로그인 페이지로 리다이렉션
오류 1차 수정했습니다. 디버깅 및 디코딩만 추가했습니다.
> 🐛 Bug: 토큰-메인연결 오류

- src/pages/GoogleCallbackPage.jsx
재로그인 시 메인 화면으로 연결
어떤 변경 사항이 있나요?
1. ## 오류 유형 확인 및 해결 과정
1. 문제 파악
- 디코딩을 통해 찾은 문제 원인 : 우리는 토큰에서 isProfileComplete를 찾고 있었지만, 실제 토큰에는 idProfileComplete라는 이름으로 저장되어 있었음.
- undefined 값을 체크하게 되어 항상 false로 평가됨
- 결과적으로 기존 사용자임에도 불구하고 항상 닉네임 페이지로 리다이렉션
2. 해결 방안 
if (decodedToken.idProfileComplete)  // 올바른 속성 이름으로 변경
3. 수정 근거 
- 콘솔에 출력된 디코딩된 토큰 정보를 확인
- JWT 토큰의 payload에 idProfileComplete가 있는 것을 확인
- 백엔드에서 생성한 토큰의 구조를 반영
- 진행 상황 전달을 위해 현재 생기는 오류들과 원인을 공유드리고 있습니다. 문의 사항이 생기면 언제든 물어봐주세요!
- 바쁘신데 확인해주셔서 감사합니다!
> 🐛 Bug: 메인-토큰 오류에서 토큰 속성 변경

- src/apis/questionApi.js
- src/components/HomePage/ImageSlider/ImageSlider.jsx
- [API] : 메인 화면에서 최근 5문제 이미지 제공
(배포까지 성공 후에  이슈 삭제할 예정 )
- Clone #79 
어떤 변경 사항이 있나요?
1. ## 작업 내용
- 문제 상황
- 예상되는 원인
1. 토큰 전송 문제
Authorization 헤더가 올바른 형식으로 전송되지 않을 수 있음
Bearer 토큰 형식이 올바르지 않을 수 있음
2. 토큰 저장 문제
localStorage에 토큰이 제대로 저장되지 않았을 수 있음
토큰이 만료되었을 수 있음
3. 서버 인증 처리 문제
Spring Security가 토큰을 제대로 해석하지 못하는 상황
UserDetails 객체를 찾지 못하는 상황
- 로그인이 필수인 기능이라, 배포 요청드립니다. 감사합니다!
> 🐛 Bug: 메인 화면 500에러 해결을 위한 디버깅 코드 추가

- src/components/HomePage/CreditButton/CreditButton.jsx
- src/pages/HomePage.jsx
#41 진행중
삭제 안 된 이슈 닫기용
- Closes #42 
- Closes #79 
어떤 변경 사항이 있나요?
1. ## 메인화면 사용자 닉네임 api 연결
2. ## 메인화면 크레딧 개수 api 연결
- 메인 화면의 사용자 정보 불러오기 API 작업입니다. 
- 해당 PR 머지 후, 성공적이면 이슈는 이후에 닫겠습니다.
> ✨  Feat: 메인화면 사용자 정보 api 연결 진행

- src/apis/myPage/index.js
- src/components/common/Loading.jsx
- src/pages/MyPage.jsx
- Closes #84 
어떤 변경 사항이 있나요?
1. 마이페이지 api 연동
2. 로딩 컴포넌트 msg prop 추가
@sumhillj
> ✨ Feat : 마이페이지 api 연동

- src/apis/userApi.js
- src/components/HomePage/CreditButton/CreditButton.jsx
- src/pages/HomePage.jsx
- 메인 화면 사용자 정보 및 크레딧 정보 불러오기
어떤 변경 사항이 있나요?
1. ## 작업 내용
GET /api/users/nickname 500 에러
GET /api/credits 500 에러
- 인증 토큰 문제:
> 토큰이 헤더에 제대로 포함되지 않음
> 토큰 형식이 잘못됨 (Bearer 접두사 누락 등)
> 만료된 토큰 사용
- 데이터 구조 불일치:
> 프론트엔드가 response.data.nickname을 찾는데, 실제 응답은 result.nickName 구조
> 크레딧 조회 시 response.data.credits를 찾는데, 실제 응답은 result.totalCredit 구조
- 해결 방안 
> API 호출 방식 수정
> 인증 토큰 처리 개선 
> 디버깅 강화 
- 메인 화면에 뜨는 500에러 해결을 위한 코드 수정을 했습니다.
> 🐛 Fix: 메인 화면 500에러 해결을 위한 코드 수정 및 디버깅 강화

- src/apis/userApi.js
- src/components/HomePage/CreditButton/CreditButton.jsx
- src/components/HomePage/CreditButton/CreditButton.module.css
- src/styles/HomePage/HomePage.module.css
- 메인 화면 사용자 정보 500오류 해결 
1. ## 작업 내용
> 현재 발생하는 문제
GET /api/users/nickname 500 에러
GET /api/credits 500 에러
서버 에러 메시지: "Cannot invoke "org.springframework.security.core.userdetails.UserDetails.getUsername()" because "userDetails" is null"
> 예상 원인
API 요청 헤더에 'Bearer ' 접두사가 없이 토큰이 전송되고 있음
이로 인해 서버가 토큰을 인증 토큰으로 인식하지 못함
결과적으로 서버에서 인증된 사용자 정보(UserDetails)를 찾지 못하는 상황
> 해결 방안
API 요청 시 Authorization 헤더에 'Bearer ' 접두사를 추가
userApiDebug.js 파일을 만들어 모든 API 요청에 일관된 인증 처리 적용
디버깅 기능을 통해 API 호출 과정 모니터링
2. ## 작업 내용
-
> 🐛 Fix : Bearer 토큰 자동 추가 기능 구현

- src/apis/userApi.js
메인화면 사용자 정보 불러오기 오류 해결
어떤 변경 사항이 있나요?
1. ## 작업 내용
> 발생하는 문제:
GET /api/users/nickname 500 에러
GET /api/credits 500 에러
서버 에러 메시지: "Cannot invoke "org.springframework.security.core.userdetails.UserDetails.getUsername()" because "userDetails" is null"
> 원인:
API 요청 시 Authorization 헤더에 토큰이 제대로 포함되지 않음
이로 인해 서버가 사용자를 인증하지 못하는 상황
SecurityConfig에서 해당 엔드포인트들이 인증이 필요한 상태
> 해결 방안:
axios 인터셉터를 사용하여 모든 API 요청에 자동으로 토큰 포함
토큰 형식을 'Bearer {token}' 형태로 전송
디버깅 로그를 추가하여 문제 발생 시 원인 파악 용이하게 개선
- 현재 사용자 정보에 따른 토큰 오류를 해결하고 있습니다! 해결 후 메인 화면 팝업 api 연결할 예정입니다.
> 🐛 Fix: 토큰 형식을 'Bearer {token}' 형태로 전송

- src/components/rankingPage/UserCard.jsx
- src/pages/RankingPage.jsx
- Closes #
어떤 변경 사항이 있나요?
1. ## 작업 내용
-
> ✨ Feat: 1등급경쟁 api 연동중

- src/apis/userApi.js
메인화면 사용자 정보 및 크레딧 정보 불러오기 
어떤 변경 사항이 있나요?
1. ## 작업 내용
- 토큰 문제 해결을 위한 디버깅 추가
- 로컬스토리지의 토큰 불러오기 
-
> 🐛Fix:  메인화면 500 토큰 오류 해결

- src/apis/myPage/index.js
- Closes #
어떤 변경 사항이 있나요?
1. 토큰명 token->accessToken으로 변경
> 🐛 Fix : 토큰 이름 token->accessToken으로 변경

- src/pages/RandomQuestionPage.jsx
- Closes #
어떤 변경 사항이 있나요?
1. ## 작업 내용
token -> accessToken
-
> 🐛 Fix: 토큰 이름 변경

- src/apis/mathApi.js
- src/components/HomePage/FullPopup/FullPopup.jsx
메인페이지 팝업 오류 해결
어떤 변경 사항이 있나요?
1. ## 메인 페이지 오류 해결
주요 개선사항
1. 백엔드 에러 코드에 따른 구체적인 에러 메시지 처리
2. 로딩 상태 관리 추가
3. 에러 상태에 대한 UI 개선
4. 타입 검증 강화
- 크레딧 오류는 일단, 오류 발생 시 10개로 뜨게 설정했습니다. 메인 팝업 수정 후에 마무리 할 예정입니다.
>  🐛Fix: 팝업 오류 해결을 위한 에러 해결

- src/components/HomePage/FullPopup/FullPopup.jsx
- src/components/HomePage/FullPopup/FullPopup.module.css
메인 팝업창 api 연결
어떤 변경 사항이 있나요?
1. ## 작업 내용
- 기존에는 이미지를 불러오는 걸로 알고 있었는데, 텍스트가 넘어온다는 걸 디버깅으로 확인
- 텍스트를 받아오는 것으로 수정완료
- 현재 답까지는 출력됩니다.
> 🐛 Fix : 팝업 이미지 => 텍스트 출력으로 변경 

- src/components/HomePage/FullPopup/FullPopup.jsx
메인화면 팝업 api 오류 해결 
어떤 변경 사항이 있나요?
1. ## 디버깅 내용 수정 
- mathService.getQuestionData()가 이미 axios response에서 data를 추출해서 반환하고 있습니다.
- 따라서 FullPopup에서는 response.data가 아닌 response 자체를 사용해야 합니다.
- 오류 수정했습니다.
>  🐛 Fix : 이중 요청 수정

- src/apis/mathApi.js
- src/components/HomePage/FullPopup/FullPopup.jsx
메인 팝업 오류 해결 
어떤 변경 사항이 있나요?
1. ## 오류 해결 
문제 상황
1. FullPopup에서 답이 표시되지 않음
2. 메모 내용이 표시되지 않음
3. "Cannot read properties of undefined (reading 'isSuccess')" 에러 발생
원인 
API 응답 구조와 데이터 처리 불일치
API 응답: {isSuccess, code, message, result: {answer, memo, note, questionImg}}
FullPopup이 잘못된 데이터 구조를 가정하고 있었음
메모를 이미지로 처리하려 했으나, 실제로는 텍스트로 옴
>  🐛 Fix : 응답구조와 데이터 불일치 오류 해결 

- src/apis/userApi.js
- 크레딧 오류 해결 
어떤 변경 사항이 있나요?
1. ## 엔드포인트가 2개인데, 다른 엔드포인트로 변경
>  🐛 Fix : 크레딧 엔드 포인트 변경

- src/pages/RankingPage.jsx
- Closes #
어떤 변경 사항이 있나요?
1. ## 작업 내용
-
> 🐛 Fix: 랭킹페이지 토큰수정

- src/pages/RandomQuestionPage.jsx
- Closes #
어떤 변경 사항이 있나요?
1. ## 작업 내용
-
> 🐛 Fix: 랜덤문제페이지 토큰수정

- src/pages/RandomPage.jsx
- src/pages/RandomQuestionPage.jsx
- Closes #
어떤 변경 사항이 있나요?
1. ## 작업 내용
-
> 🐛 Fix: 랜덤문제페이지 보수중

- src/components/afterShootingPage/SimilarQuestionModal.jsx
- src/components/global/CustomButton.jsx
- src/components/similarQuestionPage/ExplanationCard.jsx
- src/components/storagePage/StorageImages.jsx
- src/styles/global/customButton.module.css
- src/styles/similarQuestionPage/explanationCard.module.css
어떤 변경 사항이 있나요?
1. ## 크레딧 api연동
2. 저장소에서 홈으로 돌아가기 navigate연결
3. 버튼 컴포넌트 css 수
-
> ✨ Feat: 크레딧 api연동, css수정

- src/pages/RankingPage.jsx
- Closes #
어떤 변경 사항이 있나요?
1. ## 작업 내용
-
> ✨ Feat: 특정 에러코드시 더미모드 활성화

- src/pages/RankingPage.jsx
> ✨ Feat: 특정 에러코드시 더미모드 활성화2

- src/components/afterShootingPage/SimilarQuestionModal.jsx
- src/components/global/LoadingImage.jsx
- src/components/similarQuestionPage/ExplanationCard.jsx
- src/components/similarQuestionPage/GenerateImage.jsx
- Closes #90 
어떤 변경 사항이 있나요?
1. ## Latex기호를 katex 라이브러리로 정상적으로 보이도록 처리
2. 유사문제 생성을 Latex가 $...$ 로 감싸져 오는 수식을 HTML로 렌더링한 후,
* html2canvas를 통해 캡쳐하여 이미지 데이터 URL을 반환하는 함수로 리펙토링
-
> 🐛 Fix: latex 버그 수정

- src/components/storagePage/ProblemCard.jsx
어떤 변경 사항이 있나요?
1. ## 저장소에서 사진을 클릭하면 메인 페이지의 컵포넌트가 뜨도록 함
-
> ✨Feat: 저장소 이미지 클릭시 fullPopup 에 연결

- src/components/afterShootingPage/NoteCard.jsx
- src/components/similarQuestionPage/ExplanationCard.jsx
- src/styles/afterShootingPage/noteCard.module.css
- src/styles/afterShootingPage/noteSection.module.css
- src/styles/similarQuestionPage/explanationCard.module.css
- Closes #138 
어떤 변경 사항이 있나요?
1. ## 촬영 이후 페이지의 컴포넌트를 오늘의 3문제와 UI&UX 동일하게 수정
2. css를 적용 화면에 맞게 수정
-
> ♻️ Refactor: UI&UX 동일하게 수정

- src/pages/RandomPage.jsx
- src/styles/randomPage/EmptyRandomPage.module.css
- src/styles/randomPage/RandomProblem.module.css
- src/styles/randomPage/RandomQuestionPage.module.css
- Closes #132 
- Closes #49 
어떤 변경 사항이 있나요?
1. ## 작업 내용
- 저장된 문제가 없을 경우, 랜덤문제 3개를 불러올 수가 없어서 404에러가 뜨므로 해당 경우에만 EmptyRandomPage를 렌더링하도록 함
- 랜덤3문제페이지의 RandomPage & RandomQuestionPage에 있는 문제 컨테이너의 비율 고정으로 반응형을 개선함
-
> 🎨 Design: 랜덤3문제페이지 반응형 개선

- src/styles/randomPage/RandomProblem.module.css
- src/styles/randomPage/RandomQuestionPage.module.css
> 🎨 Design: 랜덤3문제페이지 문제 컨테이너 반응형 개선2

- src/components/afterShootingPage/NoteCard.jsx
- src/components/afterShootingPage/SimilarQuestionModal.jsx
- src/components/global/CustomButton.jsx
- src/components/storagePage/ProblemCard.jsx
- src/styles/afterShootingPage/noteCard.module.css
- src/styles/afterShootingPage/questionSection.module.css
- src/styles/global/customButton.module.css
- src/styles/similarQuestionPage/similarQuestionImage.module.css
- src/styles/storagePage/problemCard.module.css
- src/styles/storagePage/storageImages.module.css
- Closes #69 
어떤 변경 사항이 있나요?
1. 버튼 컴포넌트 아이패드 시작 화면 넓이부터 기존 버튼이 1.3배로 증가하고 폰트 사이즈가 16px이 되도록 수정했습니다.
2. 사진 크기 등등 ui 반응형 추가
-
> 🎨 Design:  아이패드 반응형 css 수정

- src/styles/randomPage/Handwriting.module.css
- Closes #
어떤 변경 사항이 있나요?
1. ## 작업 내용
-
> 🎨 Design: 필기노트 controls 개선

- src/styles/randomPage/Handwriting.module.css
> 🎨 Design: 필기노트 controls 개선2

- src/styles/randomPage/Handwriting.module.css
> 🎨 Design: 필기노트 controls 개선3

- src/components/similarQuestionPage/ExplanationCard.jsx
- src/components/similarQuestionPage/GenerateImage.jsx
- src/styles/afterShootingPage/noteCard.module.css
어떤 변경 사항이 있나요?
1. 정답칸에 답 : 텍스트 추가
2. 유사문제 이미지 생성 높이 추가
-
> 🎨 Design: 유사문제 이미지 높이 설정, 정답 ui 수정

- src/components/afterShootingPage/NoteCard.jsx
- src/styles/afterShootingPage/noteCard.module.css
어떤 변경 사항이 있나요?
1. 공학용 계산기 위치 고정
-
> 🎨 Design: 공학용 계산기 위치 고정

- package-lock.json
- package.json
- src/components/HomePage/FullPopup/FullPopup.module.css
- src/components/HomePage/ImageSlider/ImageSlider.jsx
- src/components/HomePage/ImageSlider/ImageSlider.module.css
- src/components/HomePage/SmallPopup/SmallPopup.jsx
- src/components/HomePage/SmallPopup/SmallPopup.module.css
Reverts UMC-7th-A1Grade/FrontEnd#163
충돌 난건 아닌데, api 문제 생겨서 리버트합니당
> Revert "🐛 Fix : 1차 QA에 따른 메인화면 반응형 수정"

- src/components/HomePage/FullPopup/FullPopup.module.css
- src/components/HomePage/LinkCameraButton/LinkCameraButton.module.css
- src/components/HomePage/RandomQusetionButton/RandomQuestionButton.module.css
- src/components/HomePage/SemicircleMessage/SemicircleMessage.module.css
- src/components/HomePage/SlideCircle/SlideCircle.module.css
- src/styles/HomePage/HomePage.module.css
메인화면 반응형 수정
어떤 변경 사항이 있나요?
1. ## 작업 내용
- 메인화면에서 버튼끼리 맞닿는 거 방지
- 메인화면 전체 반응형 추가 ( 컴포넌트가 너무 많아서 ㅠ 오래걸렸습니다)
- 팝업 ui 개선만 내일 오전 중으로 마무리 하겠습니다.
>  🐛 Fix : 1차 QA에 따른 메인화면 반응형

- src/components/HomePage/SmallPopup/SmallPopup.jsx
- src/pages/HomePage.jsx
메인 화면 반응형 구현
어떤 변경 사항이 있나요?
1. ## 작업 내용
- 스몰 모달에서 반응형 적용이 안되고 있는 오류 해결
- 큰 모달에서 답이 정중앙에 있는 오류는 회의 끝나고 수정하겠습니다
>  🐛 Fix : small 팝업창 반응형 오류 해결 완료

- src/pages/HomePage.jsx
메인 페이지 api 오류 해결
어떤 변경 사항이 있나요?
1. ## 작업 내용
- 바보같이 더미데이터 넣은 버전으로 push했습니다. 바로 수정했습니다. 
-
>  🐛 Fix : 메인 페이지 이미지 api 오류 해결

- src/components/HomePage/FullPopup/FullPopup.jsx
- src/components/HomePage/FullPopup/FullPopup.module.css
- src/components/HomePage/SmallPopup/SmallPopup.jsx
- src/components/HomePage/SmallPopup/SmallPopup.module.css
- src/pages/HomePage.jsx
- src/styles/HomePage/HomePage.module.css
QA - 메인화면 태블릿에서 사이즈 비율 키우기 
어떤 변경 사항이 있나요?
1. ## 작업 내용
- 태블릿에서의 사이즈를 키웠습니다.
- 그런데 실제 기기 체험해본게 아니라서 정확도가 낮을 수 있습니다. 
-
>  🐛 Fix : 메인 페이지 태블릿에서 반응형 키우기

- src/components/HomePage/FullPopup/FullPopup.jsx
- src/components/HomePage/FullPopup/FullPopup.module.css
- src/components/HomePage/SmallPopup/SmallPopup.jsx
- src/components/HomePage/SmallPopup/SmallPopup.module.css
- src/pages/HomePage.jsx
- src/styles/HomePage/HomePage.module.css
메인 => 로그인 리다이렉트 
어떤 변경 사항이 있나요?
1. ## 작업 내용
- 로그인 하지 않은 사용자는 로그인 페이지로 이동
-
> 🐛 Fix : 메인 => 로그인 리다이렉트

- src/pages/RandomQuestionPage.jsx
- Closes #
어떤 변경 사항이 있나요?
1. ## 작업 내용
콘솔 디버깅 코드 표시 및 api 수정작업중
-
> 🐛 Fix: 답안제출 디버깅

- src/components/randomPage/AnswerModal.jsx
- Closes #
어떤 변경 사항이 있나요?
1. ## 작업 내용
-
> 🎨 Design: 제출 후 모달 디자인 수정

- src/components/randomPage/SolutionModal.jsx
- src/pages/RandomPage.jsx
- Closes #
어떤 변경 사항이 있나요?
1. ## 작업 내용
- 돌아가기 버튼(또는 AnswerModal의 돌아가기 버튼)을 눌러 이전 페이지로 돌아갈 때, 타이머가 작동 중이면 최초에 로드된 3개의 문제가 그대로 표시되도록 적용함.
- SolutionModal에서도 LaTeX 문법을 렌더링할 수 있도록 수정함.
-
> ♻️ Refactor: 랜덤3문제페이지 보완 및 리팩토링

- src/apis/axios.js
- src/apis/mathApi.js
- src/apis/userApi.js
- src/components/HomePage/FullPopup/FullPopup.jsx
- src/pages/HomePage.jsx
- src/styles/HomePage/HomePage.module.css
어떤 변경 사항이 있나요?
1. ## 작업 내용
- 메인화면ui 반응형 일부 수정
-
>   🎨 Design: 메인화면 ui 수정
